### ISSUE TITLE
ImportError with libGL.so.1 when running rtsp-capture example locally

### ISSUE THREAD

**Issue by corybarr** [landing-ai/landingai-python#130]
Hello. I'm trying to run the rtsp-capture example locally. I'm on Windows 10 using WSL. I get this error when running [these steps](https://landing-ai.github.io/landingai-python/landingai.html#run-examples-locally). This is my first attempt at running LandingLens outside of the web browser, so user error is a possibility. Thank you.

(landingai-py3.10) user@User:~/projects$ python landingai-python/examples/capture-service/run.py
Traceback (most recent call last):
  File "/home/user/projects/landingai-python/examples/capture-service/run.py", line 4, in <module>
    from landingai.pipeline.image_source import NetworkedCamera
  File "/home/user/projects/landingai-python/landingai/pipeline/__init__.py", line 6, in <module>
    import landingai.pipeline.image_source as image_source
  File "/home/user/projects/landingai-python/landingai/pipeline/image_source.py", line 19, in <module>
    import cv2
  File "/home/user/.cache/pypoetry/virtualenvs/landingai-VV9COTnl-py3.10/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/user/.cache/pypoetry/virtualenvs/landingai-VV9COTnl-py3.10/lib/python3.10/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

**Comment by corybarr** [comment]
Running `apt install libgl1-mesa-glx` seems to have done the trick. I've installed WSL for the first time to run these examples.

**Comment by corybarr** [comment]
For anyone coming across this using WSL, the best solution for me was to not use WSL. It was very easy to run it in Windows via Powershell with some slight permissions changes. I just went with WSL because it was in the docs.
